apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: evicted-pod-reaper-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: evicted-pod-reaper-role
subjects:
- kind: ServiceAccount
  name: evicted-pod-reaper
  namespace: default