{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "evicted-pod-reaper.fullname" . }}
  labels:
    {{- include "evicted-pod-reaper.labels" . | nindent 4 }}
  {{- with include "evicted-pod-reaper.annotations" . }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "evicted-pod-reaper.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "evicted-pod-reaper.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
