apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "evicted-pod-reaper.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "evicted-pod-reaper.labels" . | nindent 4 }}
  {{- with include "evicted-pod-reaper.annotations" . }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "evicted-pod-reaper.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "evicted-pod-reaper.selectorLabels" . | nindent 8 }}
        {{- with .Values.commonLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "evicted-pod-reaper.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        image: {{ include "evicted-pod-reaper.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - --health-probe-bind-address={{ .Values.controller.healthProbeBindAddress }}
        - --metrics-bind-address={{ .Values.controller.metricsBindAddress }}
        {{- if .Values.controller.leaderElection }}
        - --leader-elect
        - --leader-election-id={{ include "evicted-pod-reaper.leaderElectionID" . }}
        {{- end }}
        env:
        {{- include "evicted-pod-reaper.envVars" . | nindent 8 }}
        ports:
        - name: metrics
          containerPort: {{ trimPrefix ":" .Values.controller.metricsBindAddress }}
          protocol: TCP
        - name: health
          containerPort: {{ trimPrefix ":" .Values.controller.healthProbeBindAddress }}
          protocol: TCP
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          {{- with .Values.livenessProbe }}
          httpGet:
            path: {{ .httpGet.path }}
            port: health
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          timeoutSeconds: {{ .timeoutSeconds }}
          successThreshold: {{ .successThreshold }}
          failureThreshold: {{ .failureThreshold }}
          {{- end }}
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          {{- with .Values.readinessProbe }}
          httpGet:
            path: {{ .httpGet.path }}
            port: health
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          timeoutSeconds: {{ .timeoutSeconds }}
          successThreshold: {{ .successThreshold }}
          failureThreshold: {{ .failureThreshold }}
          {{- end }}
        {{- end }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.extraVolumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}