{{- if and .Values.metrics.enabled .Values.metrics.podMonitor.enabled .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "evicted-pod-reaper.fullname" . }}
  namespace: {{ default .Release.Namespace .Values.metrics.podMonitor.namespace }}
  labels:
    {{- include "evicted-pod-reaper.labels" . | nindent 4 }}
    {{- with .Values.metrics.podMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with include "evicted-pod-reaper.annotations" . }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "evicted-pod-reaper.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
  - port: metrics
    path: /metrics
    {{- with .Values.metrics.podMonitor.interval }}
    interval: {{ . }}
    {{- end }}
    {{- with .Values.metrics.podMonitor.scrapeTimeout }}
    scrapeTimeout: {{ . }}
    {{- end }}
    {{- with .Values.metrics.podMonitor.honorLabels }}
    honorLabels: {{ . }}
    {{- end }}
    {{- with .Values.metrics.podMonitor.metricRelabelings }}
    metricRelabelings:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.metrics.podMonitor.relabelings }}
    relabelings:
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
