{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ include "evicted-pod-reaper.rbacBindingKind" . }}
metadata:
  name: {{ include "evicted-pod-reaper.fullname" . }}
  {{- if not .Values.reaper.watchAllNamespaces }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "evicted-pod-reaper.labels" . | nindent 4 }}
  {{- with include "evicted-pod-reaper.annotations" . }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ include "evicted-pod-reaper.rbacKind" . }}
  name: {{ include "evicted-pod-reaper.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "evicted-pod-reaper.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}